[package]
name = "codevar-truetype-emoji-color"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true

[lib]
name = "codevar_truetype_emoji_color"

[dependencies]
codevar-logger = { workspace = true }
codevar-truetype-core = { workspace = true }
codevar-truetype-sfnt = { workspace = true }
codevar-truetype-glyf = { workspace = true }
codevar-truetype-smooth = { workspace = true }
codevar-truetype-gzip = { workspace = true }

[lints]
workspace = true
