[package]
name = "codevar-truetype-raster"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true

[lib]
name = "codevar_truetype_raster"

[dependencies]
codevar-logger = { workspace = true }
codevar-truetype-core = { workspace = true }
ash = { workspace = true }
libc = { workspace = true }
