[package]
name = "codevar-ocl-lex"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true

[lib]
name = "codevar_ocl_lex"

[dependencies]
unicode-ident = { workspace = true }

[lints]
workspace = true
