[package]
name = "codevar-logger"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true

[lib]
name = "codevar_logger"

[dependencies]
cfg-if = { workspace = true }
libc = { workspace = true }
windows-link = { workspace = true }
spin = { workspace = true }
codevar-time-util = { workspace = true }
codevar-console-util = { workspace = true }
codevar-io = { workspace = true }

[target.'cfg(windows)'.dependencies]
windows = { version = "0.62", features = ["Win32_Foundation", "Win32_System_Console", "Win32_Storage_FileSystem"] }