[package]
name = "codevar-ocl-asm"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true

[lib]
name = "codevar_ocl_asm"

[dependencies]
codevar-ocl-ir = { workspace = true }

[dev-dependencies]
codevar-ocl-parse = { workspace = true }
codevar-ocl-sar = { workspace = true }

[lints]
workspace = true
