[package]
name = "codevar-launcher"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
ash = { workspace = true }
spin = { workspace = true }
libc = { workspace = true }
codevar-tlsf-alloc = { workspace = true }
codevar-base = { workspace = true }
codevar-gpu-core = { workspace = true }
codevar-wl-protocol = { workspace = true }
codevar-sig-module-base = { workspace = true }
codevar-sig-handler = { workspace = true }
codevar-env = { workspace = true }
codevar-logger = { workspace = true }

[[bin]]
name = "codevar"
path = "src/bin/main.rs"

[lints]
workspace = true
