[package]
name = "codevar-xdg-portal"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true

[lib]
name = "codevar_xdg_portal"

[dependencies]
cfg-if = { workspace = true }
libc = { workspace = true }
windows-link = { workspace = true }
spin = { workspace = true }
log = { workspace = true }
codevar-dbus = { workspace = true }
codevar-base = { path = "../codevar-base" }