[package]
name = "codevar-truetype-smooth"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true

[lib]
name = "codevar_truetype_smooth"

[dependencies]
log = { workspace = true }
codevar-truetype-core = { workspace = true }

[lints]
workspace = true
