[package]
name = "codevar-truetype-sfnt"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true

[lib]
name = "codevar_truetype_sfnt"

[dependencies]
log = { workspace = true }
codevar-truetype-core = { workspace = true }
codevar-truetype-gzip = { workspace = true }
codevar-truetype-psnames = { workspace = true }
