[package]
name = "codevar-truetype"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true

[lib]
name = "codevar_truetype"

[dependencies]
codevar-logger = { workspace = true }
codevar-truetype-core = { workspace = true }
codevar-truetype-gzip = { workspace = true }
codevar-truetype-raster = { workspace = true }
codevar-truetype-smooth = { workspace = true }
codevar-truetype-sfnt = { workspace = true }
codevar-truetype-psnames = { workspace = true }
codevar-truetype-pshinter = { workspace = true }
codevar-truetype-autofit = { workspace = true }
codevar-truetype-glyf = { workspace = true }
