[package]
name = "codevar-truetype-gzip"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true

[lib]
name = "codevar_truetype_gzip"

[features]
default = []

[dependencies]
spin = { workspace = true }
codevar-logger = { workspace = true }
codevar-truetype-core = { workspace = true }

[lints]
workspace = true
