[package]
name = "codevar-ocl-sar"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true

[lib]
name = "codevar_ocl_sar"

[dependencies]
codevar-ocl-lex = { workspace = true }
codevar-ocl-parse = { workspace = true }
codevar-console-util = { workspace = true }

[lints]
workspace = true
