[package]
name = "codevar-pathbuf"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true

[lib]
name = "codevar_pathbuf"

[features]
default = []
wasm = []
web-sys = ["dep:web-sys", "dep:wasm-bindgen"]

[dependencies]
cfg-if = { workspace = true }
libc = { workspace = true }
web-sys = { version = "0.3", features = ["console"], optional = true }
wasm-bindgen = { version = "0.2", optional = true }

[target.'cfg(windows)'.dependencies]
windows = { version = "0.62", features = ["Win32_Foundation", "Win32_Storage_FileSystem"] }