[package]
name = "codevar-ui-core"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true

[lib]
name = "codevar_ui_core"

[dependencies]
ash = { workspace = true }
codevar-base = { workspace = true }
codevar-wl-protocol = { workspace = true }
libc = { workspace = true }

[target.'cfg(windows)'.dependencies]
windows-link = { workspace = true }