[package]
name = "codevar-sig-handler"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true

[features]
nightly = []
default = []
defmt = ["dep:defmt"]
async = []
wasm = []

[lib]
name = "codevar_sig_handler"

[dependencies]
libc = { workspace = true }
heapless = { workspace = true }
codevar-textlike-encode = { workspace = true, optional = true }
codevar-io = { workspace = true }
codevar-pretty-unwind = { workspace = true }
codevar-unwinding = { workspace = true }
codevar-console-util = { workspace = true }
defmt = { workspace = true, optional = true }
spin = { workspace = true }
cfg-if = { workspace = true }

[target.'cfg(windows)'.dependencies]
windows = { workspace = true }
windows-link = { workspace = true }

[lints]
workspace = true
