[package]
name = "codevar-consoleutil"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true

[features]
default = []
wasm = []

[lib]
name = "codevar_consoleutil"

[dependencies]
libc = { workspace = true }
heapless = { workspace = true }
codevar-textlike-encode = { workspace = true }
codevar-base = { workspace = true }
codevar-io = { workspace = true }

[target.'cfg(windows)'.dependencies]
windows = { version = "0.62", features = ["Win32_Foundation", "Win32_System_Console"] }