[package]
name = "codevar-base"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true

[lib]
name = "codevar_base"

[dependencies]
cfg-if = { workspace = true }
libc = { workspace = true }
windows-link = { workspace = true }
spin = { workspace = true }
codevar-textlike-encode = { workspace = true }