[package]
name = "codevar-base"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true

[lib]
name = "codevar_base"

[features]
nightly = []
web-sys = ["dep:web-sys", "dep:wasm-bindgen"]

[dependencies]
cfg-if = { workspace = true }
libc = { workspace = true }
windows-link = { workspace = true }
spin = { workspace = true }
codevar-textlike-encode = { workspace = true }
codevar-time-core = { workspace = true }
codevar-console-util = { workspace = true }
codevar-io = { workspace = true }
rustc-demangle = { workspace = true }
web-sys = { version = "0.3", features = ["console"], optional = true }
wasm-bindgen = { version = "0.2", optional = true }

[target.'cfg(windows)'.dependencies]
windows = { version = "0.62", features = ["Win32_Foundation", "Win32_System_Console"] }

[lints]
workspace = true
