[package]
name = "codevar-wredit"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true

[lib]
name = "codevar_wredit"

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
webpki-roots = { workspace = true }
arc-swap = { workspace = true }