[package]
name = "codevar-bin"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
ash = { workspace = true }
codevar-base = { path = "../codevar-base" }
codevar-wl-protocol = { workspace = true }
libc = { workspace = true }

[[bin]]
name = "codevar"
path = "src/bin/main.rs"